### PR TITLE
Update hello.c

### PR DESCRIPTION
**Pull request by rithesh6**
maa chuda added

### CODE REVIEW

**Comment by rithesh6** [comment]
this told to comment somrthing .... so im just trying

**Comment by rithesh6** [comment]
nimish add it fucker

**Comment by rithesh6** [comment]
jaldiiiiiii fucker

**Comment by rithesh6** [comment]
hi taru

**Comment by rithesh6** [comment]
dontttt dleeteeeee

**Comment by nimishjn** [comment]
Your commits weren't necessary. Thank you anyways :)

**Comment by rithesh6** [comment]
fuck u

**Pull request closed without merging**
